title: Andrew M Blog
description: >
  Personal blog about Data Science and Machine Learning, migrated from WordPress.

# Theme configuration
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Exclude directories and files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _posts_backup
