name: Branch Preview Deploy

on:
  push:
    branches-ignore:
      - main  # Don't create previews for main branch
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper branch handling

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Determine preview path
        id: preview-path
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            PREVIEW_PATH="pr-${{ github.event.number }}"
            echo "type=pr" >> $GITHUB_OUTPUT
          else
            # For branch pushes, use the branch name (sanitized)
            BRANCH_NAME="${{ github.ref_name }}"
            PREVIEW_PATH=$(echo "$BRANCH_NAME" | sed 's/[^a-zA-Z0-9-]/-/g' | tr '[:upper:]' '[:lower:]')
            echo "type=branch" >> $GITHUB_OUTPUT
          fi
          echo "path=$PREVIEW_PATH" >> $GITHUB_OUTPUT
          echo "Preview path: $PREVIEW_PATH"

      - name: Build Jekyll site
        env:
          JEKYLL_ENV: production
        run: |
          bundle install --jobs 4 --retry 3
          
          # Build the site with the correct baseurl for preview
          PREVIEW_PATH="${{ steps.preview-path.outputs.path }}"
          bundle exec jekyll build --baseurl "/preview/$PREVIEW_PATH"
          
          # Create the preview directory structure manually
          mkdir -p "_site_with_preview/preview/$PREVIEW_PATH"
          cp -r "_site/"* "_site_with_preview/preview/$PREVIEW_PATH/"
          
          # Create or update the preview index
          mkdir -p _site_with_preview/preview
          
          # Generate a simple preview index page
          cat > _site_with_preview/preview/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <title>Branch Previews - andrewm4894.com</title>
            <style>
              body { font-family: Arial, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; }
              h1 { color: #333; }
              .preview-item { 
                background: #f5f5f5; 
                padding: 15px; 
                margin: 10px 0; 
                border-radius: 5px; 
                border-left: 4px solid #007cba;
              }
              .preview-item a { 
                text-decoration: none; 
                color: #007cba; 
                font-weight: bold; 
                font-size: 18px;
              }
              .preview-item a:hover { text-decoration: underline; }
              .preview-meta { color: #666; font-size: 14px; margin-top: 5px; }
              .back-link { 
                display: inline-block; 
                margin-top: 20px; 
                color: #007cba; 
                text-decoration: none; 
              }
            </style>
          </head>
          <body>
            <h1>🚀 Branch Previews</h1>
            <p>Available preview deployments:</p>
            <div id="previews">
              <div class="preview-item">
                <a href="/preview/$PREVIEW_PATH/">{{ steps.preview-path.outputs.path }}</a>
                <div class="preview-meta">
                  Type: ${{ steps.preview-path.outputs.type }} | 
                  Updated: $(date -u +"%Y-%m-%d %H:%M UTC") |
                  Commit: ${{ github.sha }}
                </div>
              </div>
            </div>
            <a href="/" class="back-link">← Back to main site</a>
          </body>
          </html>
          EOF

      - name: Deploy to GitHub Pages (Branch Preview)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site_with_preview
          publish_branch: gh-pages
          keep_files: true
          cname: andrewm4894.com

      - name: Comment on PR with preview URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.issue.number;
            const previewUrl = `https://andrewm4894.com/preview/pr-${prNumber}/`;
            const indexUrl = `https://andrewm4894.com/preview/`;
            
            const comment = `🚀 **Preview deployment is ready!**
            
            **Preview URL:** ${previewUrl}
            **All previews:** ${indexUrl}
            
            This preview will be updated automatically when you push new commits to this branch.`;
            
            // Check if we already commented
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
            });
            
            const botComment = comments.find(comment => 
              comment.user.type === 'Bot' && 
              comment.body.includes('Preview deployment is ready!')
            );
            
            if (botComment) {
              // Update existing comment
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: comment
              });
            } else {
              // Create new comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: comment
              });
            }

      - name: Add branch preview summary
        run: |
          PREVIEW_PATH="${{ steps.preview-path.outputs.path }}"
          echo "## 🚀 Branch Preview Deployed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Preview URL:** https://andrewm4894.com/preview/$PREVIEW_PATH/" >> $GITHUB_STEP_SUMMARY
          echo "**All previews:** https://andrewm4894.com/preview/" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "The preview will be available in a few minutes after deployment completes." >> $GITHUB_STEP_SUMMARY 