name: Deploy Main Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-main"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Checkout current pages to preserve previews
        run: |
          # Try to download current site to preserve preview directory
          mkdir -p _current_site
          
          # This will fail on first deployment, which is fine
          curl -s -f https://andrewm4894.com/preview/ > /dev/null && \
          wget -r -np -nH -nd -P _current_site/preview https://andrewm4894.com/preview/ || \
          echo "No existing previews to preserve (this is normal for first deployment)"

      - name: Build Jekyll site
        env:
          JEKYLL_ENV: production
        run: |
          bundle install --jobs 4 --retry 3
          
          # Build the main site
          bundle exec jekyll build
          
          # Preserve any existing preview directory
          if [ -d "_current_site/preview" ] && [ "$(ls -A _current_site/preview)" ]; then
            echo "Preserving existing preview directory..."
            cp -r _current_site/preview _site/ || echo "Could not preserve previews"
          else
            echo "No previews to preserve"
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Add deployment summary
        run: |
          echo "## 🚀 Main Site Deployed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Main site:** https://andrewm4894.com" >> $GITHUB_STEP_SUMMARY
          echo "**Preview index:** https://andrewm4894.com/preview/" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Deployment includes preservation of any existing branch previews." >> $GITHUB_STEP_SUMMARY
