name: pages-preview

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read       # for checkout
  pages: write         # to deploy Pages
  id-token: write      # needed by configure-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Build with Jekyll
        env:
          JEKYLL_ENV: production
          PR_NUMBER: ${{ github.event.number }}
        run: |
          bundle install --jobs 4 --retry 3
          # For PRs, build to a preview subdirectory
          if [ -n "$PR_NUMBER" ]; then
            bundle exec jekyll build -d _site/pr-preview/pr-$PR_NUMBER --baseurl "/blog/pr-preview/pr-$PR_NUMBER"
          else
            bundle exec jekyll build -d _site
          fi

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Configure Pages
        uses: actions/configure-pages@v4

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Comment PR with preview URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.issue.number;
            const previewUrl = `https://${context.repo.owner}.github.io/${context.repo.repo}/pr-preview/pr-${prNumber}/`;
            const comment = `🚀 Preview deployment is ready!\n\nYou can view your changes at: ${previewUrl}`;
            
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: comment
            });
